### ISSUE TITLE
TypeError: cannot pickle 'generator' object

### ISSUE THREAD

**Issue by anandology** [anandology/pycle#2]
Looks like `cloudpickle` doesn't support pickling generator objects.  How hard would it be to pickle generator objects?

## Traceback

```
$ python -m pycle -c 'import pathlib; files = pathlib.Path(".").iterdir()'
Traceback (most recent call last):
  File "/Users/anand/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/anand/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/anand/github/anandology/pycle/pycle/__main__.py", line 4, in <module>
    main()
  File "/Users/anand/github/anandology/pycle/pycle/pycle.py", line 59, in main
    pycle.execute(args.code)
  File "/Users/anand/github/anandology/pycle/pycle/pycle.py", line 19, in execute
    self.env.save()
  File "/Users/anand/github/anandology/pycle/pycle/env.py", line 33, in save
    pickled_value = cloudpickle.dumps(dict(self))
  File "/Users/anand/.venv/python310/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/Users/anand/.venv/python310/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 633, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'generator' object
```

**Comment by anandology** [comment]
Interesting discussion on this issue on stackoverflow:
https://stackoverflow.com/questions/7180212/why-cant-generators-be-pickled

**Comment by anandology** [comment]
> Anyway, if you need for a such feature, then look into Stackless Python which does all the above. And since Stackless’s interpreter is picklable, you also get process migration for free.
-- from the stackoverflow thread

Why am I even doing this project then? just switch to stackless python?
